name: Serverless with Python Requirements
description: JavaScript action that runs a Serverless deploy using the serverless-python-requirements plugin.

runs:
  using: node20
  main: index.js

branding:
  icon: fast-forward
  color: red

inputs:
  aws-access-key-id:
    description: AWS Access Key ID (optional). Required if using AWS credentials instead of Serverless Access Key.
    required: false
    default: ''

  aws-secret-access-key:
    description: AWS Secret Access Key (optional). Required if using AWS credentials instead of Serverless Access Key.
    required: false
    default: ''

  serverless-access-key:
    description: Serverless access key. Required if not using AWS credentials.
    required: false
    default: ''
