name: Serverless Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Serverless Deploy
        uses: dhollerbach/actions.serverless-with-python-requirements@v3
        with:
          serverless-access-key: ${{ secrets.SERVERLESS_ACCESS_KEY }}
