name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples: [
          ./examples/aws_credentials
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Serverless Deploy
        uses: ./
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          framework: 3.26.0
          working-directory: ${{ matrix.examples }}
