name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  Serverless-Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [20, 22]
        python-versions: [3.9, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Serverless Deploy
        run: |
          node index.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CONFIG_FILE: ./examples/serverless.yaml
