name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/
    strategy:
      matrix:
        node-versions: [20]
        python-versions: [3.9]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Serverless Deploy
        uses: "../"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
